### ISSUE TITLE
Send firo

### ISSUE THREAD

**Issue by moqsb** [firoorg/mobile#13]
When I send the coin to another wallet, the application stops working and then responds and sends an error message, but most of the time the message does not appear. 
![Screenshot_20220810-083649_Firo](https://user-images.githubusercontent.com/60895741/183823999-292f5b16-0623-4d73-a204-576780cb4c04.jpg)

**Comment by Stuwartserver** [comment]
i have the exact same problerm they need to find a solition asap cause my money is Locked inside app

**Comment by bouncethebox** [comment]
> i have the exact same problerm they need to find a solition asap cause my money is Locked inside app

I have the same issue but just a quick question, is your balance from transactions other than mining proceeds?

**Comment by hzak** [comment]
@moqsb please check the latest update

**Comment by moqsb** [comment]
> @moqsb please check the latest update

I will try it tonight

**Comment by moqsb** [comment]
@hzak 
it’s work now, good job 👍🏼.
