### ISSUE TITLE
Pending

### ISSUE THREAD

**Issue by moqsb** [firoorg/mobile#15]
When the problem of sending coins was fixed, a pending problem appeared before sending 

![Screenshot_20221002-042527_Firo~2](https://user-images.githubusercontent.com/60895741/193434086-81a32ee1-4e70-4135-90ee-b6490496498a.jpg)

**Comment by moqsb** [comment]
Look to the date

**Comment by hzak** [comment]
@moqsb can you please try to restore the wallet from the scratch? I've tried to investigate, but still can't understand what could be the problem of staying it "pending".
