### ISSUE TITLE
Firo wallet doesn't have any protection against screenshot and recent apps view

### ISSUE THREAD

**Issue by serrq** [firoorg/mobile#18]
While I attempted to create a new (but also with restoring) wallet I noticed that I could do screenshot of my passphrase and it was visible in recent apps view on my Android device.

This is a not safe practice. Please fix it from beginning steps in Firo wallets.

Currently I uninstalled it due security risks.

**Comment by hzak** [comment]
thanks @serrq for the suggestion, we will consider it for the next release

**Comment by hzak** [comment]
@serrq please check the recent version (0.1.23)
