### ISSUE TITLE
Restore wallet 

### ISSUE THREAD

**Issue by moqsb** [firoorg/mobile#20]
I tried to retrieve my wallet using the special words, and suddenly my wallet became new, and I have nothing, how is that?

**Comment by justanwar** [comment]
Please try restoring it to these wallets. Make sure you double-check that you backed up the correct words.

https://github.com/cypherstack/stack_wallet
https://github.com/cypherstack/Campfire

**Comment by moqsb** [comment]
@justanwar 
I have done this now and I am sure of what I said, but at least I am supposed to see all the transfers, but I would not have seen them, and if the words were wrong, I would not have opened the wallet in the first place.

**Comment by moqsb** [comment]
@justanwar 
I have done this now and I am sure of what I said, but at least I am supposed to see all the transfers, but I would not have seen them, and if the words were wrong, I would not have opened the wallet in the first place.

**Comment by justanwar** [comment]
Yes, if the words are correct you will see some transfers. Did you write them down in the correct order?

**Comment by moqsb** [comment]
I tried Campfire and everything worked. Thank you very much @justanwar
