### ISSUE TITLE
Move fastlane directory

### ISSUE THREAD

**Issue by PanderMusubi** [firoorg/mobile#21]
Is it okay I make a PR to move `android/metadata` to `fastlane/metadata` in order to fix an issue for building for F-Droid?

See also https://gitlab.com/fdroid/rfp/-/issues/1972#note_1502117740 and https://gitlab.com/-/snippets/1895688#locations

Would moving this directory break anything and/or does something else needs to be updated when this directory is moved?

**Comment by reubenyap** [comment]
We actually want to sunset this wallet once Stack Wallet & Campfire is fully working since it was always intended to be a reference implementation. As Stack and Campfire are FOSS and GPL licensed, makes more sense for them to maintain it rather than expend additional development resources on it.

**Comment by PanderMusubi** [comment]
Thanks, for reference see https://gitlab.com/fdroid/rfp/-/issues/1972#note_1504691839
