### ISSUE TITLE
Remove dependencies blocking building for F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [firoorg/mobile#22]
Remove dependencies blocking building for F-Droid:
- `com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}` (Tracker)
- `com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}` (Tracker)
- `com.facebook.flipper:flipper:${FLIPPER_VERSION}` (Tracker)

Remove permissions blocking building for F-Droid:
- `com.google.android.c2dm.permission.RECEIVE` (NonFreeDep,Tracking)
- `com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE` (NonFreeDep,Tracking)

Remove URLs blocking building for F-Droid:
- `https://www.facebook.com/sharer/sharer.php?u=`
- `https://play.google.com/store/apps/details?id=com.instagram.android`
- `https://plus.google.com/`
- `https://plus.google.com/share?url=`

Perhaps also remove references to;
- Facebook
- Instagram
- Twitter
- Pinterest

It looks like some of these dependencies are not used or needed, but ended up in the build via a starting framework for the app.

See also https://gitlab.com/fdroid/rfp/-/issues/1972#note_1502117740

This would not only allow bundling for F-Droid but will make the build for Google Play safer.

**Comment by justanwar** [comment]
Per https://github.com/firoorg/mobile/issues/21#issuecomment-1669596940
