### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [firoorg/mobile#4]
Please support that this app is published in the F-Droid app store. I will post a link for the request for packaging there later.

**Comment by PanderMusubi** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1972

**Comment by PanderMusubi** [comment]
This is required for inclusion in F-Droid https://github.com/firoorg/mobile/pull/5

**Comment by PanderMusubi** [comment]
@hzak @araarakelyan1985 can you provide a long description and some screenshots please?

**Comment by PanderMusubi** [comment]
Added screenshots in https://github.com/firoorg/mobile/pull/8

**Comment by PanderMusubi** [comment]
Please have a look at the feedback in https://gitlab.com/fdroid/rfp/-/issues/1972#note_798979492 for getting this app buid by F-Droid, thanks.

**Comment by trymeouteh** [comment]
Would like this on F-Droid.

**Comment by PanderMusubi** [comment]
@serrq In case that was a question: F-Droid is an appstore like Google Play but only with FOSS apps.

**Comment by PanderMusubi** [comment]
Please see the feedback of the scan by F-Droid of the latest version at https://gitlab.com/fdroid/rfp/-/issues/1972#note_1502117740

**Comment by justanwar** [comment]
Closed per https://github.com/firoorg/mobile/issues/21#issuecomment-1669596940
