### ISSUE TITLE
Offer translation service

### ISSUE THREAD

**Issue by PanderMusubi** [firoorg/mobile#6]
Make all the strings in the app translatable via https://github.com/firoorg/mobile/blob/main/android/app/src/main/res/values/strings.xml with a free service such as Transifex, POEditor or Weblate. Preferably a translation service that is already used by other Firo software.

**Comment by PanderMusubi** [comment]
See also https://github.com/firoorg/mobile/tree/main/src/localization

**Comment by justanwar** [comment]
Closed per https://github.com/firoorg/mobile/issues/21#issuecomment-1669596940
