### ISSUE TITLE
Create Passphrase during wallet setup, confirming passphrase not working

### ISSUE THREAD

**Issue by goodc0re** [firoorg/mobile#7]
Android 11
CalyxOS 2.11.0
Pixel 5
Firo-v0.1.6.apk

During Firo wallet setup, after seed phrase generation, on the Create Passphrase screen, no matter how short or long of a passphrase I enter, confirming it via the Android keyboard results in no action / confirmation and there is otherwise no button visible on the screen to confirm my choice of passphrase. Wallet setup can not be completed.

**Comment by hzak** [comment]
@goodc0re There is a `Continue` button at the bottom of the page, which should work. Can't you hide the keyboard? Or you can hide the keyboard, but don't see the `Continue` button?

**Comment by goodc0re** [comment]
@hzak Managed to hide the keyboard to see the Continue button now. It was really easy to overlook especially because it has the same background color and is located all the way on the bottom. 

So I suppose it would still be good if the input could be confirmed with with check / ok button on the Android keyboard itself.

**Comment by hzak** [comment]
Glad to hear it's working, and thanks for the feedback, we will try to improve the UX of that screen.
